"""Initial migration

Revision ID: dd83ad78a3f6
Revises: 
Create Date: 2025-11-03 10:47:53.089168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd83ad78a3f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=False),
    sa.Column('target_pattern', sa.String(length=255), nullable=True),
    sa.Column('technique', sa.Text(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('times_successful', sa.Integer(), nullable=True),
    sa.Column('average_detection_time', sa.Float(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('client', sa.String(length=120), nullable=False),
    sa.Column('engagement_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_results', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=True),
    sa.Column('time_to_detect', sa.Float(), nullable=True),
    sa.Column('environmental_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_feedback')
    op.drop_table('scan_result')
    op.drop_table('finding')
    op.drop_table('target')
    op.drop_table('scheduled_scan')
    op.drop_table('report')
    op.drop_table('engagement')
    op.drop_table('attack_knowledge')
    # ### end Alembic commands ###
